version: '1.0.{build}'
image:
- Ubuntu1804
- Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet build -c Release
after_build:
  # For once the build has completed
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off
